services:
  - type: web
    name: gestprojects
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: une-cle-secrete-longue
      - key: GEMINI_API_KEY
        value: ta-cle-gemini