import os
if os.path.exists('.env'):
    from dotenv import load_dotenv
    load_dotenv()
_cache = {}
DOMAIN_TRANSLATIONS = {
    'Informatique': 'Computer Science',
    'Intelligence Artificielle': 'Artificial Intelligence',
    'Génie logiciel': 'Software Engineering',
    'Réseaux et Sécurité': 'Networks & Security',
    'Mobile': 'Mobile',
    'Santé': 'Health',
    'Agriculture intelligente': 'Smart Agriculture',
    'Environnement': 'Environment',
    'Éducation': 'Education',
    'Finance': 'Finance',
    'Mathématiques': 'Mathematics',
    'Physique': 'Physics',
    'Chimie': 'Chemistry',
    'Architecture': 'Architecture',
    'Droit': 'Law',
}

WORD_TRANSLATIONS = {
    # Expressions longues en premier
    'projet de recherche appliquée': 'applied research project',
    'projet de recherche': 'research project',
    'zones rurales': 'rural areas',
    'zones urbaines': 'urban areas',
    'afrique centrale': 'central africa',
    'afrique de l\'ouest': 'west africa',
    'université de douala': 'university of douala',
    'visant à développer': 'aimed at developing',
    'visant à résoudre': 'aimed at solving',
    'visant à': 'aimed at',
    'pour résoudre': 'to solve',
    'pour améliorer': 'to improve',
    'pour développer': 'to develop',
    'conditions de vie': 'living conditions',
    'pme locales': 'local smes',
    'hôpitaux publics': 'public hospitals',
    'établissements scolaires': 'schools',
    'jeunes entrepreneurs': 'young entrepreneurs',
    'solution innovante': 'innovative solution',
    'solution logicielle': 'software solution',
    'conception et implémentation': 'design and implementation',
    'recherche et développement': 'research and development',
    'en temps réel': 'in real time',
    # Mots simples
    'système': 'system',
    'systeme': 'system',
    'plateforme': 'platform',
    'application': 'application',
    'application': 'application',
    'développement': 'development',
    'developpement': 'development',
    'outil': 'tool',
    'modèle': 'model',
    'modele': 'model',
    'finance': 'finance',
    'finances': 'finances',
    'infrastructure': 'infrastructure',
    'chatbot': 'chatbot',
    'analyse': 'analysis',
    'détection': 'detection',
    'detection': 'detection',
    'reconnaissance': 'recognition',
    'suivi': 'monitoring',
    'surveillance': 'surveillance',
    'prédiction': 'prediction',
    'prediction': 'prediction',
    'classification': 'classification',
    'diagnostic': 'diagnostic',
    'traduction': 'translation',
    'recommandation': 'recommendation',
    'cartographie': 'mapping',
    'numérique': 'digital',
    'numerique': 'digital',
    'intelligent': 'intelligent',
    'intelligente': 'smart',
    'médical': 'medical',
    'medical': 'medical',
    'médicale': 'medical',
    'agricole': 'agricultural',
    'routier': 'road',
    'climatique': 'climate',
    'scolaire': 'school',
    'cameroun': 'cameroon',
    'conception': 'design',
    'implémentation': 'implementation',
    'implementation': 'implementation',
    'solution': 'solution',
    'innovante': 'innovative',
    'technologique': 'technological',
    'logicielle': 'software',
    'robuste': 'robust',
    'optimiser': 'optimize',
    'automatiser': 'automate',
    'processus': 'processes',
    'besoins': 'needs',
    'spécifiques': 'specific',
    'specifiques': 'specific',
    'pratiques': 'practices',
    'existantes': 'existing',
    'populations': 'populations',
    'locales': 'local',
    'locaux': 'local',
    'problèmes': 'issues',
    'problemes': 'issues',
    'problématiques': 'challenges',
    'problematiques': 'challenges',
    'résoudre': 'solve',
    'resoudre': 'solve',
    'développer': 'develop',
    'developper': 'develop',
    'améliorer': 'improve',
    'ameliorer': 'improve',
    'créer': 'create',
    'creer': 'create',
    'édition': 'edition',
    'edition': 'edition',
    'agriculteurs': 'farmers',
    'données': 'data',
    'donnees': 'data',
    'réseau': 'network',
    'reseau': 'network',
    'réseaux': 'networks',
    'reseaux': 'networks',
    'sécurité': 'security',
    'securite': 'security',
    'apprentissage': 'learning',
    'automatique': 'automatic',
    'profond': 'deep',
    'vocale': 'voice',
    'fraude': 'fraud',
    'épidémique': 'epidemic',
    'epidemique': 'epidemic',
    'monitorage': 'monitoring',
    'paiement': 'payment',
    'télémédecine': 'telemedicine',
    'telemedecine': 'telemedicine',
    'cadastral': 'cadastral',
    'foncière': 'land',
    'fonciere': 'land',
    'numérisation': 'digitization',
    'numerisation': 'digitization',
    'contraintes': 'constraints',
    'connectivité': 'connectivity',
    'connectivite': 'connectivity',
    'adaptée': 'adapted',
    'adaptee': 'adapted',
    'intégrant': 'integrating',
    'integrant': 'integrating',
    'dernières': 'latest',
    'dernieres': 'latest',
    'technologies': 'technologies',
    'complète': 'complete',
    'complete': 'complete',
    'ciblé': 'targeted',
    'cible': 'targeted',
    'secteur': 'sector',
    'contexte': 'context',
    'africain': 'african',
    'moderniser': 'modernize',
    'spécifique': 'specific',
    'specifique': 'specific',
    # Prépositions et petits mots
    'pour': 'for',
    'avec': 'with',
    'dans': 'in',
    'sur': 'on',
    'par': 'by',
    'et': 'and',
    'ou': 'or',
    'de': 'of',
    'du': 'of the',
    'des': 'of the',
    'les': 'the',
    'le': 'the',
    'la': 'the',
    'un': 'a',
    'une': 'a',
    'en': 'in',
    'au': 'to the',
    'aux': 'to the',
    'qui': 'that',
    'à': 'to',
    'ce': 'this',
    'permettant': 'allowing',
    'permettant à': 'allowing',
    'étudiants': 'students',
    'etudiant': 'student',
    'étudiant': 'student',
    'etudiants': 'students',
    'gérer': 'manage',
    'gerer': 'manage',
    'gestion': 'management',
    'leurs': 'their',
    'theurs': 'their',
    'finances': 'finances',
    'financement': 'financing',
    'financier': 'financial',
    'financière': 'financial',
    'aux': 'to the',
    'leur': 'their',
    'ses': 'its',
    'mon': 'my',
    'ton': 'your',
    'son': 'his',
    'notre': 'our',
    'votre': 'your',
    'qui': 'that',
    'que': 'that',
    'dont': 'whose',
    'où': 'where',
    'quand': 'when',
    'comment': 'how',
    'pourquoi': 'why',
    'très': 'very',
    'tres': 'very',
    'bien': 'well',
    'mal': 'badly',
    'aussi': 'also',
    'encore': 'still',
    'déjà': 'already',
    'deja': 'already',
    'toujours': 'always',
    'jamais': 'never',
    'souvent': 'often',
    'parfois': 'sometimes',
    'utilisateurs': 'users',
    'utilisateur': 'user',
    'entreprise': 'company',
    'entreprises': 'companies',
    'université': 'university',
    'universite': 'university',
    'faculté': 'faculty',
    'faculte': 'faculty',
    'étude': 'study',
    'etude': 'study',
    'études': 'studies',
    'etudes': 'studies',
    'cours': 'courses',
    'formation': 'training',
    'apprentissage': 'learning',
    'enseignement': 'teaching',
    'enseignant': 'teacher',
    'enseignants': 'teachers',
    'professeur': 'professor',
    'professeurs': 'professors',
    'budget': 'budget',
    'dépenses': 'expenses',
    'depenses': 'expenses',
    'revenus': 'income',
    'économies': 'savings',
    'economies': 'savings',
    'compte': 'account',
    'comptes': 'accounts',
    'banque': 'bank',
    'bancaire': 'banking',
    'paiement': 'payment',
    'paiements': 'payments',
    'transaction': 'transaction',
    'transactions': 'transactions',
    'mobile': 'mobile',
    'application mobile': 'mobile application',
    'web': 'web',
    'site web': 'website',
    'interface': 'interface',
    'tableau de bord': 'dashboard',
    'rapport': 'report',
    'rapports': 'reports',
    'statistiques': 'statistics',
    'analyse': 'analysis',
    'analyses': 'analyses',
    'résultats': 'results',
    'resultats': 'results',
    'objectif': 'objective',
    'objectifs': 'objectives',
    'tâche': 'task',
    'tache': 'task',
    'tâches': 'tasks',
    'taches': 'tasks',
    'projet': 'project',
    'projets': 'projects',
    'équipe': 'team',
    'equipe': 'team',
    'membres': 'members',
    'membre': 'member',
    'rôle': 'role',
    'role': 'role',
    'accès': 'access',
    'acces': 'access',
    'connexion': 'connection',
    'inscription': 'registration',
    'authentification': 'authentication',
    'mot de passe': 'password',
    'identifiant': 'identifier',
    'profil': 'profile',
    'notification': 'notification',
    'notifications': 'notifications',
    'message': 'message',
    'messages': 'messages',
    'envoi': 'sending',
    'réception': 'reception',
    'reception': 'reception',
    'stockage': 'storage',
    'base de données': 'database',
    'serveur': 'server',
    'client': 'client',
    'api': 'API',
    'interface graphique': 'graphical interface',
    'logiciel': 'software',
    'matériel': 'hardware',
    'materiel': 'hardware',
    'réseau': 'network',
    'internet': 'internet',
    'cloud': 'cloud',
    'sécurisé': 'secure',
    'securise': 'secure',
    'chiffré': 'encrypted',
    'chiffre': 'encrypted',
    'protégé': 'protected',
    'protege': 'protected',
    'privé': 'private',
    'prive': 'private',
    'public': 'public',
    'ouvert': 'open',
    'fermé': 'closed',
    'ferme': 'closed',
    'actif': 'active',
    'inactif': 'inactive',
    'disponible': 'available',
    'indisponible': 'unavailable',
    'gratuit': 'free',
    'payant': 'paid',
    'abonnement': 'subscription',
}



def auto_translate(text: str) -> str:
    """Traduit un texte français vers l'anglais."""
    if not text or not text.strip():
        return text

    # 1. Domaine exact connu
    if text.strip() in DOMAIN_TRANSLATIONS:
        return DOMAIN_TRANSLATIONS[text.strip()]

    # 2. Cache
    cache_key = hash(text.strip())
    if cache_key in _cache:
        return _cache[cache_key]

    # 3. Gemini API
    try:
        from google import genai
        api_key = os.environ.get('GEMINI_API_KEY')
        print(f"DEBUG clé: {api_key[:10] if api_key else 'AUCUNE CLÉ'}")
        if api_key:
            client = genai.Client(api_key=api_key)
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=(
                    "Translate this French text to English. "
                    "Return ONLY the translation, no explanation:\n\n" + text
                )
            )
            result = response.text.strip()
            _cache[cache_key] = result
            return result
    except Exception as e:
        print(f"DEBUG erreur Gemini: {e}")
        pass
    
    # 4. Fallback dictionnaire
    result = text.lower()
    sorted_translations = sorted(
        WORD_TRANSLATIONS.items(),
        key=lambda x: len(x[0]),
        reverse=True
    )
    for fr, en in sorted_translations:
        result = result.replace(fr, en)
    result = ' '.join(result.split())
    return result.capitalize()